name: lakehouse

networks:
  wba-network:
    driver: bridge

volumes:
  minio-data:
    name: minio-data 
    driver: local

services: 
  # MinIO (Enterprise Object Store)
  minio:
    hostname: minio
    container_name: minio
    image: minio/minio:RELEASE.2024-11-07T00-52-20Z
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./minio-data:/data
    environment:
      MINIO_ROOT_USER: accesskey
      MINIO_ROOT_PASSWORD: secretkey
    command: server /data --console-address ":9001"
    networks:
      - wba-network

  # Apache Superset (Data Visualization) connected with DuckDB (Querying Storage)
  superset:
    container_name: superset-duckdb
    image: superset-duckdb:latest
    ports:
        - "8088:8088"
    volumes:
      - ./duckdb-data:/app/data
      - ./superset-data:/app/superset_home
    command: bash -c 
      "superset fab create-admin --username admin --firstname Superset --lastname Admin --email admin@superset.com --password admin &&
       superset db upgrade &&
       superset init &&
       superset set_database_uri -d DuckDB -u 'duckdb:///data/duck.db' &&
       /usr/bin/run-server.sh"
    networks:
      - wba-network
